### ISSUE TITLE
Cannot make it to run

### ISSUE THREAD

**Issue by probablyys** [Jaic1/xv6-riscv-rust#2]
I have followed the instructions in *README.md* to compile this project, it ended up no errors while compiling but there is a file `fs.img` missing so that qemu cannot be started. Did I miss anything?

**Comment by Jaic1** [comment]
Sry for the doc being not clear.
As a temp solution, maybe you can try to make it in [xv6](https://github.com/mit-pdos/xv6-riscv)
and copy it to the current project's root dir.
Also note that `xv6-riscv-rust` currently is not runnable yet. (but I might update it soon :)
